version: '3.1'

services:

  wordpress:
    image: "wordpress:${WP_TAG}"
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_TABLE_PREFIX: ${WP_PREFIX}
      WORDPRESS_DEBUG: ${WP_DEBUG}
    volumes:
      - ./wordpress:/var/www/html
      - ./themes:/var/www/html/wp-content/themes/
      - ./plugins:/var/www/html/wp-content/plugins/
      - ./uploads:/var/www/html/wp-content/uploads/

  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: nazarpc/phpmyadmin
    ports:
      - 1234:80
    links:
      - db:mysql
